spring:

    config:
        #change the extraInfoExample to extraInfo with its credentials
        import: optional:extraInfo.yml 

    datasource:
        url: jdbc:mysql://localhost:3306/dental_moovi?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ${dataBasePasswordMySQL}
        driver-class-name: com.mysql.cj.jdbc.Driver

    sql:
        init:
            mode: always
            continue-on-error: false

    mail:
        host: ${mailHost}
        port: 587
        protocol: smtp
        username: ${email}
        password: ${mailPassword}
        otherPassword: ${OtherMailPassword}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
            schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
            table-name: SPRING_SESSION
    
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

server:
    port: 8087
    servlet:
        session:
            cookie:
                http-only: true
            timeout: 20m
    error:
        include-message: always

jwt:
    secret: ${jwtSecret}
    expiration: ${expirationJWT}
    accessTokenByCookieName: ${jwtCookie}

logging:
    level:
        org:
            springframework:
                data:
                    jdbc:
                        core: DEBUG