server:
    port: 8087

spring:

    config:
        #change the extraInfoExample to extraInfo with its credentials
        import: optional:extraInfo.yml 

    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://localhost:3306/dental_moovi
        username: root
        password: ${dataBasePasswordMySQL}
        driver-class-name: com.mysql.cj.jdbc.Driver

logging:
    level:
        '[org.hibernate.SQL]': DEBUG